import { Milestone, WbsPackage } from '../models/project.models';

export const SCHEDULE_CONTENT = {
  eyebrow: 'Project Schedule & WBS',
  title: 'Timeline & Work Breakdown',
  wbsRoot: 'The Green Hub Sustainable Community Center',
  duration: '40 Weeks',
  startDate: '1 January 2026',
  finishDate: '2 October 2026',
  ganttTitle: 'Project Schedule (Gantt Chart) — 40 Weeks',
  wbs: [
    {
      id: 1,
      title: 'Project Initiation',
      weeks: '1–2',
      color: '#3b82f6',
      tasks: [
        'Project Charter',
        'Stakeholder Identification',
        'Feasibility Study',
        'Initial Budget Estimate',
      ],
    },
    {
      id: 2,
      title: 'Planning & Design',
      weeks: '3–5',
      color: '#06b6d4',
      tasks: [
        'Requirements Gathering',
        'Conceptual Design',
        'Detailed Design',
        'Approvals & Permits',
        'Project Plan Development',
      ],
    },
    {
      id: 3,
      title: 'Procurement',
      weeks: '6–11',
      color: '#22c55e',
      tasks: [
        'Supplier Selection',
        'Material Procurement',
        'Equipment Procurement',
        'Contracting',
      ],
    },
    {
      id: 4,
      title: 'Construction & Infrastructure',
      weeks: '12–22',
      color: '#84cc16',
      tasks: [
        'Site Preparation',
        'Building Construction',
        'MEP Installation',
        'Interior Finishes',
        'External Works',
        'Quality Control & Inspection',
      ],
    },
    {
      id: 5,
      title: 'Renewable Energy Systems Installation',
      weeks: '23–29',
      color: '#eab308',
      tasks: [
        'Solar PV System Installation',
        'Backup Energy Systems',
        'System Testing & Commissioning',
      ],
    },
    {
      id: 6,
      title: 'Smart Building System (BMS) Development',
      weeks: '14–24',
      color: '#f97316',
      tasks: [
        'System Design',
        'Software Development',
        'Integration',
        'Testing & Commissioning',
      ],
    },
    {
      id: 7,
      title: 'Water Conservation Systems Installation',
      weeks: '25–32',
      color: '#a855f7',
      tasks: [
        'Rainwater Harvesting',
        'Greywater Recycling',
        'System Testing & Commissioning',
      ],
    },
    {
      id: 8,
      title: 'Community & Educational Programs Setup',
      weeks: '28–35',
      color: '#ec4899',
      tasks: [
        'Program Planning',
        'Content Development',
        'Partnerships & Outreach',
        'Program Launch',
      ],
    },
    {
      id: 9,
      title: 'Testing, Commissioning & Training',
      weeks: '36–38',
      color: '#64748b',
      tasks: ['System Testing', 'Staff Training', 'User Training'],
    },
    {
      id: 10,
      title: 'Project Handover & Closure',
      weeks: '39–40',
      color: '#166534',
      tasks: [
        'Final Inspection',
        'Handover to Client',
        'Documentation & Closeout',
      ],
    },
    {
      id: 11,
      title: 'Post-Project Monitoring & Evaluation',
      weeks: '33–40',
      color: '#0f766e',
      tasks: [
        'Performance Monitoring',
        'Evaluation & Reporting',
        'Continuous Improvement',
      ],
    },
  ] satisfies WbsPackage[],
  gantt: [
    { phase: 'Project Initiation', start: 1, end: 2, duration: '2 Weeks' },
    { phase: 'Planning & Design', start: 3, end: 5, duration: '3 Weeks' },
    { phase: 'Procurement', start: 6, end: 11, duration: '6 Weeks' },
    {
      phase: 'Construction & Infrastructure',
      start: 12,
      end: 22,
      duration: '11 Weeks',
    },
    {
      phase: 'Renewable Energy Systems Installation',
      start: 23,
      end: 29,
      duration: '7 Weeks',
    },
    {
      phase: 'Smart Building System (BMS) Development',
      start: 14,
      end: 24,
      duration: '11 Weeks',
    },
    {
      phase: 'Water Conservation Systems Installation',
      start: 25,
      end: 32,
      duration: '8 Weeks',
    },
    {
      phase: 'Community & Educational Programs Setup',
      start: 28,
      end: 35,
      duration: '8 Weeks',
    },
    {
      phase: 'Testing, Commissioning & Training',
      start: 36,
      end: 38,
      duration: '3 Weeks',
    },
    { phase: 'Project Handover & Closure', start: 39, end: 40, duration: '2 Weeks' },
    {
      phase: 'Post-Project Monitoring & Evaluation',
      start: 33,
      end: 40,
      duration: '8 Weeks',
    },
  ],
  milestones: [
    { title: 'Design Approval', week: 'Wk 5' },
    { title: 'Construction Completion', week: 'Wk 22' },
    { title: 'Systems Commissioning', week: 'Wk 38' },
    { title: 'Project Handover', week: 'Wk 40' },
  ] satisfies Milestone[],
  totalWeeks: 40,
};
