import { Localized } from '../i18n/language.types';
import { GanttRow, Milestone, WbsPackage } from '../models/project.models';

export interface ScheduleContent {
  eyebrow: string;
  title: string;
  wbsRoot: string;
  duration: string;
  startDate: string;
  finishDate: string;
  ganttTitle: string;
  ganttLead: string;
  wbs: WbsPackage[];
  gantt: GanttRow[];
  milestones: Milestone[];
  totalWeeks: number;
}

export const SCHEDULE_CONTENT: Localized<ScheduleContent> = {
  en: {
    eyebrow: 'Deliverable 2 & 6',
    title: 'WBS & 40-Week Schedule',
    wbsRoot: 'The Green Hub Project',
    duration: '40 Weeks',
    startDate: '1 January 2026',
    finishDate: '2 October 2026',
    ganttTitle: 'Project Schedule Overview — 40 Weeks',
    ganttLead:
      'Built from the Scope Statement’s 7-phase strategy, with WBS branches mapped along the timeline. Construction splits into overlapping sub-branches.',
    wbs: [
      {
        id: 1,
        title: 'Project Management',
        weeks: '1–40',
        color: '#3b82f6',
        tasks: [
          'Project Planning',
          'Project Scheduling',
          'Project Budgeting',
          'Monitoring & Control',
          'Project Closeout',
        ],
      },
      {
        id: 2,
        title: 'Site Preparation',
        weeks: '16–19',
        color: '#06b6d4',
        tasks: [
          'Land Survey & Analysis',
          'Site Clearing & Demolition',
          'Earthwork',
          'Foundation Work',
          'Site Utilities Preparation',
        ],
      },
      {
        id: 3,
        title: 'Construction',
        weeks: '18–28',
        color: '#22c55e',
        tasks: [
          'Building Structure',
          'Roofing',
          'Exterior Finishes',
          'Interior Finishes',
          'MEP Rough-In',
          'Fixtures & Fittings',
        ],
      },
      {
        id: 4,
        title: 'Green Systems',
        weeks: '24–32',
        color: '#84cc16',
        tasks: [
          'Solar Power System',
          'Rainwater Harvesting',
          'Smart Lighting System',
          'Smart HVAC System',
          'Recycling & Waste Management',
          'Building Management System (BMS)',
        ],
      },
      {
        id: 5,
        title: 'Landscaping & Outdoor Areas',
        weeks: '29–35',
        color: '#eab308',
        tasks: [
          'Landscape Design',
          'Outdoor Construction',
          'Irrigation System',
          'Green Spaces Development',
        ],
      },
      {
        id: 6,
        title: 'Testing & Handover',
        weeks: '36–40',
        color: '#166534',
        tasks: [
          'System Testing',
          'Final Inspection',
          'Client Handover',
          'Post Handover Support',
        ],
      },
    ],
    gantt: [
      {
        phase: 'Project Management (continuous)',
        start: 1,
        end: 40,
        duration: '40 wk',
        color: '#64748b',
        wbsRef: 'Branch 1',
      },
      {
        phase: 'Initiation',
        start: 1,
        end: 2,
        duration: '2 wk',
        color: '#3b82f6',
        wbsRef: '1.1',
      },
      {
        phase: 'Planning',
        start: 3,
        end: 5,
        duration: '3 wk',
        color: '#0ea5e9',
        wbsRef: '1.2–1.4',
      },
      {
        phase: 'Design & Engineering',
        start: 6,
        end: 11,
        duration: '6 wk',
        color: '#06b6d4',
        wbsRef: 'Branch 7',
      },
      {
        phase: 'Procurement',
        start: 12,
        end: 15,
        duration: '4 wk',
        color: '#14b8a6',
        wbsRef: 'Branch 8',
      },
      {
        phase: 'Site Preparation',
        start: 16,
        end: 19,
        duration: '4 wk',
        color: '#22c55e',
        wbsRef: 'Branch 2',
      },
      {
        phase: 'Building Construction',
        start: 18,
        end: 28,
        duration: '11 wk',
        color: '#84cc16',
        wbsRef: 'Branch 3',
      },
      {
        phase: 'Green Systems Installation',
        start: 24,
        end: 32,
        duration: '9 wk',
        color: '#eab308',
        wbsRef: 'Branch 4',
      },
      {
        phase: 'Landscaping & Outdoor Areas',
        start: 29,
        end: 35,
        duration: '7 wk',
        color: '#f59e0b',
        wbsRef: 'Branch 5',
      },
      {
        phase: 'Testing',
        start: 36,
        end: 38,
        duration: '3 wk',
        color: '#a855f7',
        wbsRef: '6.1–6.2',
      },
      {
        phase: 'Handover',
        start: 39,
        end: 40,
        duration: '2 wk',
        color: '#166534',
        wbsRef: '6.3–6.4',
      },
      {
        phase: 'Community Programs & Launch',
        start: 33,
        end: 40,
        duration: '8 wk',
        color: '#ec4899',
        wbsRef: 'Branch 9',
      },
    ],
    milestones: [
      { title: 'Design Complete', week: 'Wk 11' },
      { title: 'Procurement Locked', week: 'Wk 15' },
      { title: 'Building Structure Ready', week: 'Wk 28' },
      { title: 'Green Systems Live', week: 'Wk 32' },
      { title: 'Testing Complete', week: 'Wk 38' },
      { title: 'Project Handover', week: 'Wk 40' },
    ],
    totalWeeks: 40,
  },
  ar: {
    eyebrow: 'المخرجان 2 و 6',
    title: 'هيكل العمل وجدول 40 أسبوعًا',
    wbsRoot: 'مشروع جرين هب',
    duration: '40 أسبوعًا',
    startDate: '1 يناير 2026',
    finishDate: '2 أكتوبر 2026',
    ganttTitle: 'نظرة عامة على جدول المشروع — 40 أسبوعًا',
    ganttLead:
      'مبني على استراتيجية المراحل السبع في بيان النطاق، مع ربط فروع WBS على الخط الزمني. الإنشاء يتفرّع بتداخل واقعي.',
    wbs: [
      {
        id: 1,
        title: 'إدارة المشروع',
        weeks: '1–40',
        color: '#3b82f6',
        tasks: [
          'تخطيط المشروع',
          'جدولة المشروع',
          'ميزانية المشروع',
          'المراقبة والتحكم',
          'إغلاق المشروع',
        ],
      },
      {
        id: 2,
        title: 'تجهيز الموقع',
        weeks: '16–19',
        color: '#06b6d4',
        tasks: [
          'مسح وتحليل الأرض',
          'التطهير والهدم',
          'أعمال الحفر',
          'أعمال الأساسات',
          'تجهيز مرافق الموقع',
        ],
      },
      {
        id: 3,
        title: 'الإنشاء',
        weeks: '18–28',
        color: '#22c55e',
        tasks: [
          'هيكل المبنى',
          'الأسقف',
          'التشطيبات الخارجية',
          'التشطيبات الداخلية',
          'تمديدات MEP',
          'التركيبات والتجهيزات',
        ],
      },
      {
        id: 4,
        title: 'الأنظمة الخضراء',
        weeks: '24–32',
        color: '#84cc16',
        tasks: [
          'نظام الطاقة الشمسية',
          'حصاد مياه الأمطار',
          'الإضاءة الذكية',
          'نظام HVAC الذكي',
          'إعادة التدوير والنفايات',
          'نظام إدارة المباني (BMS)',
        ],
      },
      {
        id: 5,
        title: 'تنسيق الموقع والخارج',
        weeks: '29–35',
        color: '#eab308',
        tasks: [
          'تصميم المشهد',
          'الإنشاءات الخارجية',
          'نظام الري',
          'تطوير المساحات الخضراء',
        ],
      },
      {
        id: 6,
        title: 'الاختبار والتسليم',
        weeks: '36–40',
        color: '#166534',
        tasks: [
          'اختبار الأنظمة',
          'التفتيش النهائي',
          'التسليم للعميل',
          'الدعم بعد التسليم',
        ],
      },
    ],
    gantt: [
      {
        phase: 'إدارة المشروع (مستمرة)',
        start: 1,
        end: 40,
        duration: '40 أسبوعًا',
        color: '#64748b',
        wbsRef: 'الفرع 1',
      },
      {
        phase: 'البدء',
        start: 1,
        end: 2,
        duration: 'أسبوعان',
        color: '#3b82f6',
        wbsRef: '1.1',
      },
      {
        phase: 'التخطيط',
        start: 3,
        end: 5,
        duration: '3 أسابيع',
        color: '#0ea5e9',
        wbsRef: '1.2–1.4',
      },
      {
        phase: 'التصميم والهندسة',
        start: 6,
        end: 11,
        duration: '6 أسابيع',
        color: '#06b6d4',
        wbsRef: 'الفرع 7',
      },
      {
        phase: 'المشتريات',
        start: 12,
        end: 15,
        duration: '4 أسابيع',
        color: '#14b8a6',
        wbsRef: 'الفرع 8',
      },
      {
        phase: 'تجهيز الموقع',
        start: 16,
        end: 19,
        duration: '4 أسابيع',
        color: '#22c55e',
        wbsRef: 'الفرع 2',
      },
      {
        phase: 'بناء المبنى',
        start: 18,
        end: 28,
        duration: '11 أسبوعًا',
        color: '#84cc16',
        wbsRef: 'الفرع 3',
      },
      {
        phase: 'تركيب الأنظمة الخضراء',
        start: 24,
        end: 32,
        duration: '9 أسابيع',
        color: '#eab308',
        wbsRef: 'الفرع 4',
      },
      {
        phase: 'تنسيق الموقع والخارج',
        start: 29,
        end: 35,
        duration: '7 أسابيع',
        color: '#f59e0b',
        wbsRef: 'الفرع 5',
      },
      {
        phase: 'الاختبار',
        start: 36,
        end: 38,
        duration: '3 أسابيع',
        color: '#a855f7',
        wbsRef: '6.1–6.2',
      },
      {
        phase: 'التسليم',
        start: 39,
        end: 40,
        duration: 'أسبوعان',
        color: '#166534',
        wbsRef: '6.3–6.4',
      },
      {
        phase: 'البرامج المجتمعية والإطلاق',
        start: 33,
        end: 40,
        duration: '8 أسابيع',
        color: '#ec4899',
        wbsRef: 'الفرع 9',
      },
    ],
    milestones: [
      { title: 'اكتمال التصميم', week: 'أسبوع 11' },
      { title: 'إغلاق المشتريات', week: 'أسبوع 15' },
      { title: 'جاهزية هيكل المبنى', week: 'أسبوع 28' },
      { title: 'تشغيل الأنظمة الخضراء', week: 'أسبوع 32' },
      { title: 'اكتمال الاختبار', week: 'أسبوع 38' },
      { title: 'تسليم المشروع', week: 'أسبوع 40' },
    ],
    totalWeeks: 40,
  },
};
